[workspace]
resolver = "3"
members = ["./crates/faultforge", "./crates/faultforge-bindings", "./fuzz"]

[workspace.package]
version = "0.1.0"
edition = "2024"


[workspace.dependencies]
rayon = "1.11.0"
